### ISSUE TITLE
Add support for LLaMa 3 on Groq 

### ISSUE THREAD

**Issue by jozzy** [lmos-ai/arc#2]
Groq being the fastest inference compute , add support for models hosted in Groq. LLaMa3 

https://console.groq.com/docs/models 

There is a similar request open in Spring AI https://github.com/spring-projects/spring-ai/issues/621 

an approach to reuse such interrogations could also be thought through

**Comment by kaikreuzer** [comment]
I've created https://github.com/lmos-ai/arc/pull/51 for this.
